from typing import Any, Dict, List


class CodeTemplateEngine:
    """Generates starter code templates and file content snippets for project blueprints."""

    def generate_code_templates(self, title: str, tech_stack: Dict[str, Any]) -> Dict[str, Any]:
        primary_be = tech_stack.get("recommended_primary", {}).get("backend", "FastAPI")

        backend_main_py = f"""# {title} - Backend Entrypoint
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{title} API",
    version="1.0.0",
    description="Enterprise API generated by NeuroDesk AI Studio",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health", tags=["Health"])
async def health_check():
    return {{"status": "healthy", "service": "{title}"}}
"""

        frontend_app_jsx = f"""// {title} - Frontend Root Component
import React from 'react';

export default function App() {{
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col items-center justify-center">
      <h1 className="text-3xl font-bold text-cyan-400">{title}</h1>
      <p className="mt-2 text-slate-400">Generated with NeuroDesk AI Studio</p>
    </div>
  );
}}
"""

        docker_file = """# Production Multi-Stage Dockerfile
FROM python:3.12-slim AS backend-builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

        return {
            "backend_entrypoint": backend_main_py,
            "frontend_root": frontend_app_jsx,
            "dockerfile": docker_file,
        }


code_template_engine = CodeTemplateEngine()
