from typing import Any, Dict, List


class DatabaseDesignEngine:
    """Designs relational database entities, fields, keys, ER diagrams, and SQL DDL snippets."""

    def design_database(self, title: str, project_type: str) -> Dict[str, Any]:
        tables = [
            {
                "name": "users",
                "description": "User account credentials and role metadata",
                "columns": [
                    {"name": "id", "type": "UUID", "primary_key": True, "nullable": False},
                    {"name": "email", "type": "VARCHAR(255)", "primary_key": False, "nullable": False, "unique": True},
                    {"name": "hashed_password", "type": "VARCHAR(255)", "primary_key": False, "nullable": False},
                    {"name": "role", "type": "VARCHAR(50)", "primary_key": False, "nullable": False, "default": "'USER'"},
                    {"name": "created_at", "type": "TIMESTAMPTZ", "primary_key": False, "nullable": False},
                ],
            },
            {
                "name": "projects",
                "description": f"Core records for {title}",
                "columns": [
                    {"name": "id", "type": "UUID", "primary_key": True, "nullable": False},
                    {"name": "owner_id", "type": "UUID", "primary_key": False, "nullable": False, "foreign_key": "users.id"},
                    {"name": "title", "type": "VARCHAR(255)", "primary_key": False, "nullable": False},
                    {"name": "status", "type": "VARCHAR(50)", "primary_key": False, "nullable": False, "default": "'ACTIVE'"},
                    {"name": "metadata_json", "type": "JSONB", "primary_key": False, "nullable": False, "default": "'{}'"},
                    {"name": "created_at", "type": "TIMESTAMPTZ", "primary_key": False, "nullable": False},
                    {"name": "updated_at", "type": "TIMESTAMPTZ", "primary_key": False, "nullable": False},
                ],
            },
            {
                "name": "audit_logs",
                "description": "System event and security audit trail",
                "columns": [
                    {"name": "id", "type": "UUID", "primary_key": True, "nullable": False},
                    {"name": "user_id", "type": "UUID", "primary_key": False, "nullable": False, "foreign_key": "users.id"},
                    {"name": "action", "type": "VARCHAR(100)", "primary_key": False, "nullable": False},
                    {"name": "details_json", "type": "JSONB", "primary_key": False, "nullable": False},
                    {"name": "timestamp", "type": "TIMESTAMPTZ", "primary_key": False, "nullable": False},
                ],
            },
        ]

        relationships = [
            {"from": "users.id", "to": "projects.owner_id", "type": "1:N", "on_delete": "CASCADE"},
            {"from": "users.id", "to": "audit_logs.user_id", "type": "1:N", "on_delete": "CASCADE"},
        ]

        sql_ddl = """-- PostgreSQL DDL Generated by NeuroDesk AI DatabaseDesignEngine
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_projects_owner_id ON projects(owner_id);
"""

        return {
            "tables": tables,
            "relationships": relationships,
            "sql_ddl": sql_ddl,
        }


database_design_engine = DatabaseDesignEngine()
