import json
from typing import Any, Dict, Optional


class ExportEngine:
    """Exports AI Studio project blueprints into Markdown, JSON, YAML, and HTML formats."""

    def export_blueprint(self, blueprint_data: Dict[str, Any], fmt: str = "markdown") -> Dict[str, str]:
        fmt_clean = fmt.lower()
        title = blueprint_data.get("summary", {}).get("title", "Project Blueprint")
        file_slug = title.lower().replace(" ", "_")

        if fmt_clean == "json":
            content = json.dumps(blueprint_data, indent=2)
            filename = f"{file_slug}_blueprint.json"
        elif fmt_clean == "yaml":
            content = f"# {title} Enterprise Blueprint Specification\n"
            content += f"title: \"{title}\"\n"
            content += f"project_type: \"{blueprint_data.get('summary', {}).get('project_type')}\"\n"
            content += f"description: \"{blueprint_data.get('summary', {}).get('description')}\"\n"
            content += "requirements:\n"
            for fr in blueprint_data.get("requirements", {}).get("functional_requirements", []):
                content += f"  - id: \"{fr.get('id')}\"\n    title: \"{fr.get('title')}\"\n    description: \"{fr.get('description')}\"\n"
            filename = f"{file_slug}_blueprint.yaml"
        elif fmt_clean == "html":
            content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{title} — Software Blueprint</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #e2e8f0; background-color: #0f172a; padding: 40px; max-width: 900px; margin: 0 auto; }}
    h1 {{ color: #38bdf8; border-bottom: 2px solid #1e293b; padding-bottom: 10px; }}
    h2 {{ color: #818cf8; margin-top: 30px; }}
    .badge {{ background: #1e293b; color: #38bdf8; padding: 4px 8px; border-radius: 6px; font-size: 0.8em; font-family: monospace; }}
    .card {{ background: #1e293b; border: 1px solid #334155; padding: 16px; border-radius: 12px; margin-bottom: 16px; }}
    pre {{ background: #020617; padding: 12px; border-radius: 8px; font-family: monospace; color: #38bdf8; overflow-x: auto; }}
  </style>
</head>
<body>
  <h1>🚀 {title} Blueprint Specification</h1>
  <p><strong>Generated by:</strong> NeuroDesk AI Studio</p>
  
  <h2>📌 Executive Summary</h2>
  <div class="card"><p>{blueprint_data.get('summary', {}).get('description', '')}</p></div>

  <h2>🎯 Functional Requirements</h2>
  <ul>
"""
            for fr in blueprint_data.get("requirements", {}).get("functional_requirements", []):
                content += f"    <li><span class=\"badge\">{fr.get('id')}</span> <strong>{fr.get('title')}</strong>: {fr.get('description')}</li>\n"
            content += f"""  </ul>

  <h2>🛠️ Recommended Technology Stack</h2>
  <div class="card">
    <ul>
"""
            for cat, details in blueprint_data.get("tech_stack", {}).get("recommendations", {}).items():
                content += f"      <li><strong>{cat.title()}:</strong> {details.get('technology')} — <em>{details.get('why')}</em></li>\n"
            content += f"""    </ul>
  </div>
</body>
</html>"""
            filename = f"{file_slug}_blueprint.html"
        else:
            # Default Markdown format
            content = f"# 🚀 Enterprise Project Specification: {title}\n\n"
            content += f"> Generated by **NeuroDesk AI Studio**  \n\n"

            content += f"## 📌 Executive Summary\n"
            content += f"{blueprint_data.get('summary', {}).get('description', '')}\n\n"

            reqs = blueprint_data.get("requirements", {})
            content += f"## 🎯 Functional Requirements\n"
            for fr in reqs.get("functional_requirements", []):
                content += f"- **[{fr.get('id')}] {fr.get('title')}**: {fr.get('description')}\n"
            content += "\n"

            t_stack = blueprint_data.get("tech_stack", {})
            content += f"## 🛠️ Technology Recommendation Engine\n"
            for cat, details in t_stack.get("recommendations", {}).items():
                content += f"- **{cat.title()}**: `{details.get('technology')}` — *{details.get('why')}*\n"
            content += "\n"

            api_spec = blueprint_data.get("api_contracts", {})
            content += f"## 📡 REST API Contracts\n"
            for ep in api_spec.get("endpoints", []):
                content += f"### `{ep.get('method')}` {ep.get('path')}\n"
                content += f"{ep.get('summary')}\n\n"

            filename = f"{file_slug}_blueprint.md"

        return {
            "title": title,
            "format": fmt_clean,
            "filename": filename,
            "content": content,
        }


export_engine = ExportEngine()
